# To use this file, run `docker-compose up`.
version: '3.4'

x-backend-config: &backend
  build:
    context: "./scripts/docker"
    dockerfile: "Dockerfile.backend"

services:
  # Main application
  backend:
    <<: *backend
    volumes:
      - .:/usr/src/app

  # Migration service
  migration:
    <<: *backend
    volumes:
      - .:/usr/src/app

  frontend:
    stdin_open: true
    build:
      context: "."
      dockerfile: "./scripts/docker/Dockerfile.frontend_development"
      args:
        - TM_APP_API_URL=http://localhost/api
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm start
    environment:
      - TM_APP_API_URL=http://localhost/api
    labels:
      - traefik.http.routers.frontend.rule=Host(`localhost`)
      - traefik.http.services.frontend.loadbalancer.server.port=3000
